### ISSUE TITLE
Not working for non-targeted nameplates

### ISSUE THREAD

**Issue by GittyBruce** [bkader/NameplateSCT_WoTLK#5]
Hello, thank you for your work on the addon so far. There's currently a problem where damage doesn't appear on nameplates that have not been targeted. 

Related video below. Notice how the dmg only appears after a target has been selected at least once. Should the nameplate go offscreen, the target needs to selected again for dmg to appear.

Edit: Github isn't cooperating with the video it seems. But let me if the description is unclear.

**Comment by bkader** [comment]
Hello @GittyBruce .. Nameplates in 3.3.5 don't have _GUIDs_ assigned to them, they need to be determined and cached first and this **requires** you to target them, mouseover them or focus them. Once those _GUIDs_ are cached, the addon works because the damage parsed from the **combat log** uses those _GUIDs_ to attach damage to nameplates.
