### ISSUE TITLE
Addon randomly stops working

### ISSUE THREAD

**Issue by stefanmrvic** [bkader/NameplateSCT_WoTLK#7]
After few secs of playing, addon stop working on 90% of the mobs. Only after disabling and re-enabling addon it starts to work again, but stops shorty after.

**Comment by bkader** [comment]
Here are **3 minutes** of combat and constant target changing.

https://user-images.githubusercontent.com/4732702/168471420-9837ab83-4d30-4b32-a7a7-07c57d120b40.mp4

**Comment by stefanmrvic** [comment]
Here is the first example of the bug (it occurs on the second mob)
https://user-images.githubusercontent.com/61718109/168483744-3cbc8288-a771-4d80-be00-255b3cf5f64a.mp4

And here is the second example of the bug:
https://user-images.githubusercontent.com/61718109/168484232-5b57cbab-a831-46e4-8034-4442aaf809cf.mp4

**Comment by bkader** [comment]
@stefanmrvic try to update the addon, I updated Nameplates library, then make sure to quickly mouseover nameplates before engaging them, 3.3.5 doesn't have a _decent_ nameplates API, workarounds had/have to be done.

Since you are using **ElvUI**, here is another **01:30** combat with ElvUI enabled and notice how it works fine when **GUIDs** are cached and this only happens when you have valid unitIDs (_mouseover, focus, target ..._)

https://user-images.githubusercontent.com/4732702/168485509-f63951be-797c-45dc-84b3-6c7638687d68.mp4

**Comment by stefanmrvic** [comment]
I don't know what you did, but now when I'm in a group or in a dungeon, damage numbers displays for the whole group above the NPC nameplate, not just mine damage (spells + auto attack), but of the whole group.
